import {
  X,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Plus,
  Minus,
  Pencil,
  Trash2,
  MoreVertical,
  Search,
  Info,
  TriangleAlert,
  CircleX,
  ChevronUp,
  Settings,
  Hammer,
  Compass,
  Target,
  Anchor,
  BookOpen,
  Repeat,
  Clock,
  CalendarCheck,
  Mountain,
  Flag,
  Construction,
  Shield,
  Notebook,
  Moon,
  Activity,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconRegistry = {
  close: X,
  check: Check,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  add: Plus,
  minus: Minus,
  edit: Pencil,
  delete: Trash2,
  more: MoreVertical,
  search: Search,
  info: Info,
  warning: TriangleAlert,
  error: CircleX,
  success: Check,
  settings: Settings,
  building: Hammer,
  structured_learning: BookOpen,
  exploring: Compass,
  practicing: Target,
  habit: Repeat,
  maintaining: Anchor,
  depth_of_focus: Target,
  time_invested: Clock,
  challenge_stretch: Mountain,
  progress_realized: Flag,
  reflection_captured: Notebook,
  consistency_adherence: CalendarCheck,
  curiosity_pull: Compass,
  friction_encountered: Construction,
  resilience: Shield,
  recovery_quality: Moon,
  decay_check: Activity,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
